<?php

/**
 * @file
 * Contains node_links.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function node_links_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the node_links module.
    case 'help.page.node_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
